version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_new
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
